default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: outboxer_app_development

test:
  <<: *default
  database: outboxer_app_test

# production:
#   <<: *default
#   database: outboxer_app_production
#   username: your_username
#   password: your_password
